version: '2.1'
orbs:
  codecov: codecov/codecov@3.1.1
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coverage
          command: npm run test
      - codecov/upload:
           file: './coverage/clover.xml'
          token: 3998d015-de84-41c6-8533-681b577446cf

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
 
