version: '2.1'
orbs:
  codecov: codecov/codecov@3.0.0
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coverage
          command: npm run test -- --coverage
      - codecov/upload:
          file: coverage/*.json

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
 
 
 
